version: '3.1'

services:
  mongo:
    image: mongo
    restart: on-failure
    volumes:
      - mongodata:/data/db

  mongo-express:
    image: mongo-express
    restart: on-failure
    ports:
      - 8081:8081

  plumber:
    image: plumber-api-img
    restart: on-failure
    environment:
      STAGES_QTY: 1

volumes:
  mongodata: {}
