version: '3.1'

services:

  stage-01:
    hostname: stage-01
    build: stage-01/
    restart: on-failure
    deploy:
      replicas: 1
    environment:
      CONCURRENT_SCRIPTS: 1
      IDLE: 60
      PIPELINE_NAME: test-api
      STAGE: 1
    volumes:
      - ./stage-01/scripts/:/plumber/scripts/
    command: /plumber/run-scripts.sh
