version: '3.1'

services:

  stage-01:
    hostname: stage-01
    build: stage-01/
    restart: on-failure
    deploy:
      replicas: 1 # Single container
    environment:
      CONCURRENT_SCRIPTS: 1
      IDLE: 43200 # Run scripts every 12H
      PIPELINE_NAME: alexa-subdomains-capture
      STAGE: 1
    volumes:
      - ./stage-01/scripts/:/plumber/scripts/
    command: /plumber/run-scripts.sh

  stage-02:
    hostname: stage-02
    build: stage-02/
    restart: on-failure
    deploy:
      replicas: 3 # Set of 3 containers
    environment:
      CONCURRENT_SCRIPTS: 1
      IDLE: 0 # No delay between runs
      PIPELINE_NAME: alexa-subdomains-capture
      STAGE: 2
    volumes:
      - ./stage-02/scripts/:/plumber/scripts/
    command: /plumber/run-scripts.sh

  stage-03:
    hostname: stage-03
    build: stage-03/
    restart: on-failure
    deploy:
      replicas: 10 # Set of 10 containers
    environment:
      CONCURRENT_SCRIPTS: 1
      IDLE: 0 # No delay between runs
      PIPELINE_NAME: alexa-subdomains-capture
      STAGE: 3
    volumes:
      - ./stage-03/scripts/:/plumber/scripts/
      - /tmp/captures/:/tmp/captures/
    command: /plumber/run-scripts.sh
